openapi: 3.0.3
info:
    title: Data application proxy
    description: A service for proxing requests/authorization to data applications using Keboola components.
    version: "1.0"
servers:
    - url: https://appsproxy.{stack}
      variables:
        stack:
            enum:
                - keboola.com
                - eu-central-1.keboola.com
                - north-europe.azure.keboola.com
                - eu-west-1.aws.keboola.dev
                - east-us-2.azure.keboola-testing.com
            default: keboola.com
    - url: http://localhost:8000
paths:
    /:
        get:
            tags:
                - appsproxy
            summary: Redirect to /_proxy
            description: Redirect to /_proxy.
            operationId: ApiRootIndex
            responses:
                "301":
                    description: Moved Permanently response.
    /_proxy:
        delete:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "3"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        get:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: Proxy
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        patch:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "6"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        post:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "1"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        put:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "2"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
    /_proxy/{path}:
        delete:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "3"
            parameters:
                - name: path
                  in: path
                  required: true
                  schema:
                    type: string
                    description: '"Path that proxies to data application".'
                    example: ""
                  example: ""
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        get:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: ProxyPath
            parameters:
                - name: path
                  in: path
                  required: true
                  schema:
                    type: string
                    description: '"Path that proxies to data application".'
                    example: ""
                  example: ""
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        patch:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "6"
            parameters:
                - name: path
                  in: path
                  required: true
                  schema:
                    type: string
                    description: '"Path that proxies to data application".'
                    example: ""
                  example: ""
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        post:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "1"
            parameters:
                - name: path
                  in: path
                  required: true
                  schema:
                    type: string
                    description: '"Path that proxies to data application".'
                    example: ""
                  example: ""
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
        put:
            tags:
                - appsproxy
            summary: Proxying endpoint for data applications
            description: This endpoint proxies (accepts) all requests and redirects them to the data application.
            operationId: "2"
            parameters:
                - name: path
                  in: path
                  required: true
                  schema:
                    type: string
                    description: '"Path that proxies to data application".'
                    example: ""
                  example: ""
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: abc123
                            example: abc123
    /v1/:
        get:
            tags:
                - documentation
            summary: List API name and link to documentation.
            description: List API name and link to documentation.
            operationId: ApiVersionIndex
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceDetail'
                            example:
                                api: appsproxy
                                documentation: https://appsproxy.keboola.com/v1/documentation
    /v1/documentation/openapi.json:
        get:
            tags:
                - documentation
            summary: Swagger 2.0 JSON Specification
            operationId: OpenapiJson
            responses:
                "200":
                    description: File downloaded
    /v1/documentation/openapi.yaml:
        get:
            tags:
                - documentation
            summary: Swagger 2.0 YAML Specification
            operationId: OpenapiYaml
            responses:
                "200":
                    description: File downloaded
    /v1/documentation/openapi3.json:
        get:
            tags:
                - documentation
            summary: OpenAPI 3.0 JSON Specification
            operationId: Openapi3Json
            responses:
                "200":
                    description: File downloaded
    /v1/documentation/openapi3.yaml:
        get:
            tags:
                - documentation
            summary: OpenAPI 3.0 YAML Specification
            operationId: Openapi3Yaml
            responses:
                "200":
                    description: File downloaded
    /v1/validate:
        get:
            tags:
                - appsproxy
            summary: Validation of OIDC authorization provider configuration
            description: Validation endpoint of OIDC authorization provider configuration.
            operationId: Validate
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Validations'
                            example:
                                configuration:
                                    - exampleerrordata:
                                        statusCode: 404
                                        error: validations incorrect
                                        message: unable to validate due to missing entry
                                      id: test
                                      name: My Template
            security:
                - storage-api-token: []
components:
    schemas:
        Configuration:
            type: object
            properties:
                clientID:
                    type: string
                    description: Client ID of provider.
                    example: github.oidc
                clientSecret:
                    type: string
                    description: Client secret provided by OIDC provider.
                    example: thisissupersecret
                id:
                    type: string
                    description: Unique ID of provider.
                    example: oidc#1
            description: The configuration that is part of the auth providers section.
            example:
                clientID: github.oidc
                clientSecret: thisissupersecret
                id: oidc#1
            required:
                - id
                - clientID
                - clientSecret
        ServiceDetail:
            type: object
            properties:
                api:
                    type: string
                    description: Name of the API
                    example: appsproxy
                documentation:
                    type: string
                    description: URL of the API documentation.
                    example: https://appsproxy.keboola.com/v1/documentation
            example:
                api: appsproxy
                documentation: https://appsproxy.keboola.com/v1/documentation
            required:
                - api
                - documentation
        Validations:
            type: object
            properties:
                configuration:
                    type: array
                    items:
                        $ref: '#/components/schemas/Configuration'
                    description: All authorization providers.
                    example:
                        - exampleerrordata:
                            statusCode: 404
                            error: validations incorrect
                            message: unable to validate due to missing entry
                          id: test
                          name: My Template
            example:
                configuration:
                    - exampleerrordata:
                        statusCode: 404
                        error: validations incorrect
                        message: unable to validate due to missing entry
                      id: test
                      name: My Template
    securitySchemes:
        storage-api-token:
            type: apiKey
            description: Storage Api Token Authentication.
            name: X-StorageApi-Token
            in: header
tags:
    - name: apps-proxy
      description: Service for proxing requests/authorization to data applications using Keboola data app component.
